INSERT INTO vibetribe.location (city_name) VALUES
('Aceh Besar'),
('Banda Aceh'),
('Langsa'),
('Lhokseumawe'),
('Sabang'),
('Bireuen'),
('Pidie'),
('Simeulue'),
('Nias'),
('Gunungsitoli'),
('Medan'),
('Binjai'),
('Pematangsiantar'),
('Sibolga'),
('Tanjungbalai'),
('Langkat'),
('Deli Serdang'),
('Serdang Bedagai'),
('Karo'),
('Simalungun'),
('Asahan'),
('Batubara'),
('Toba Samosir'),
('North Tapanuli'),
('South Tapanuli'),
('Padang'),
('Bukittinggi'),
('Payakumbuh'),
('Solok'),
('Sijunjung'),
('Dharmasraya'),
('Pasaman'),
('Pasaman Barat'),
('Bengkulu'),
('Bengkulu Utara'),
('Bengkulu Selatan'),
('Rejang Lebong'),
('Lebong'),
('Kaur'),
('Seluma'),
('Muko Muko'),
('Jambi'),
('Jambi City'),
('Batanghari'),
('Muaro Jambi'),
('Tanjung Jabung Barat'),
('Tanjung Jabung Timur'),
('Kerinci'),
('Sungai Penuh'),
('Bungo'),
('Sarolangun'),
('Tebo'),
('Palembang'),
('Prabumulih'),
('Pagar Alam'),
('Lahat'),
('Muara Enim'),
('Ogan Ilir'),
('Ogan Komering Ilir'),
('Banyuasin'),
('Musi Banyuasin'),
('Musi Rawas'),
('Empat Lawang'),
('Lampung'),
('Bandar Lampung'),
('Metro'),
('Lampung Selatan'),
('Lampung Tengah'),
('Lampung Utara'),
('Way Kanan'),
('Tanggamus'),
('Pesawaran'),
('Pringsewu'),
('Banten'),
('Serang'),
('Cilegon'),
('Tangerang'),
('Tangerang Selatan'),
('Lebak'),
('Pandeglang'),
('Jakarta'),
('Jakarta Pusat'),
('Jakarta Utara'),
('Jakarta Barat'),
('Jakarta Selatan'),
('Jakarta Timur'),
('Bogor'),
('Depok'),
('Bekasi'),
('Sukabumi'),
('Cianjur'),
('Karawang'),
('Purwakarta'),
('Subang'),
('Indramayu'),
('Majalengka'),
('Sumedang'),
('Cirebon'),
('Kuningan'),
('Brebes'),
('Cilacap'),
('Banyumas'),
('Purbalingga'),
('Banjarnegara'),
('Kebumen'),
('Purworejo'),
('Wonosobo'),
('Magelang'),
('Temanggung'),
('Semarang'),
('Salatiga'),
('Sragen'),
('Karanganyar'),
('Boyolali'),
('Klaten'),
('Sukoharjo'),
('Wonogiri'),
('Grobogan'),
('Blora'),
('Rembang'),
('Pati'),
('Kudus'),
('Jepara'),
('Demak'),
('Batang'),
('Pekalongan'),
('Pemalang'),
('Tegal'),
('Yogyakarta'),
('Sleman'),
('Bantul'),
('Gunungkidul'),
('Kulon Progo'),
('Surakarta'),
('Sukoharjo'),
('Karanganyar'),
('Wonogiri'),
('Bandung'),
('Cimahi'),
('Bekasi'),
('Sumedang'),
('Sukabumi'),
('Cirebon'),
('Tasikmalaya'),
('Garut'),
('Ciamis'),
('Kuningan'),
('Majalengka'),
('Banyumas'),
('Cilacap'),
('Purwokerto'),
('Malang'),
('Kediri'),
('Blitar'),
('Probolinggo'),
('Pasuruan'),
('Banyuwangi'),
('Jember'),
('Lumajang'),
('Situbondo'),
('Bondowoso'),
('Sampang'),
('Pamekasan'),
('Sumenep'),
('Madiun'),
('Ngawi'),
('Ponorogo'),
('Pacitan'),
('Trenggalek'),
('Tulungagung'),
('Nganjuk'),
('Jombang'),
('Kediri'),
('Bojonegoro'),
('Lamongan'),
('Gresik'),
('Sidoarjo'),
('Mojokerto'),
('Bali'),
('Denpasar'),
('Badung'),
('Tabanan'),
('Buleleng'),
('Karangasem'),
('Jembrana'),
('Gianyar'),
('Bangli'),
('Nusa Penida'),
('NTB'),
('Mataram'),
('Lombok Barat'),
('Lombok Tengah'),
('Lombok Timur'),
('Sumbawa'),
('Dompu'),
('Bima'),
('Sumbawa Barat'),
('Nusa Tenggara Timur'),
('Kupang'),
('Ende'),
('Flores Timur'),
('Sikka'),
('Ngada'),
('Manggarai'),
('Manggarai Barat'),
('Nagekeo'),
('Sumba Timur'),
('Sumba Barat'),
('Alor'),
('Lembata'),
('Rote Ndao'),
('Belu'),
('Maluku'),
('Ambon'),
('Maluku Tengah'),
('Maluku Tenggara'),
('Buru'),
('Buru Selatan'),
('Seram Bagian Barat'),
('Seram Bagian Timur'),
('Papua'),
('Jayapura'),
('Sarmi'),
('Keerom'),
('Biak Numfor'),
('Paniai'),
('Nduga'),
('Mimika'),
('Dogiyai'),
('Intan Jaya'),
('Deiyai'),
('Puncak'),
('Puncak Jaya'),
('Yahukimo'),
('Tolikara'),
('Lanny Jaya'),
('Nabire'),
('Boven Digoel'),
('Mappi'),
('Asmat'),
('West Papua'),
('Manokwari'),
('Sorong'),
('Raja Ampat'),
('South Sorong'),
('Maybrat'),
('Teluk Bintuni'),
('Teluk Wondama'),
('Kaimana'),
('Fakfak'),
('Bintuni'),
('Mansel');
